# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eder Elorriaga
title: Senior Software Developer
email: eder.elorriaga@gmail.com
website: gexplorer.org

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  geplorer
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ederelorriaga
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Download resume
  icon: fas fa-file-pdf
  url: https://docs.google.com/document/d/1AS2kMpy6ajcWt35E38a44tImd2FCL43KHjXLhrpEe6g/export?format=pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: |
  I'm a computer geek with a knack for problem solving.

  Very interested in UX with years of experience with **angular** and **Vue**, and some experience with **React**.

  In the backend most of my experience is in **.Net** and **java**, and lately I've been working with **nodejs**.
   
  **Linux** power user ever since I discovered Open Source in college. I try to give back to the OS community as much as I can. Defender of good practices and **agile** methodologies. I learned **functional programming** by tinkering with lisp while learning to use Emacs.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Gamevy
        link: g.games
        sub_title: Developer
        caption: September 2020 - Present
        description: |
          I became completely **remote** in Gamevy.
          - I developed an engine to easily create backends for slot games in **nodejs**
          - I learned how to create very intensive tests with the help of **AWS clusters** and **docker**

      - layout: left
        title: Plain Concepts
        link: www.plainconcepts.com
        sub_title: Developer
        caption: February 2016 - September 2020
        description: |
          I developed some interesting projects in Plain concepts, more focused on **frontend** challenges.
          - I switched from java to **.Net** for the backend
          - I learned about the inner workings of **Angular** by migrating an Angular 2 project to Angular 9 and refactoring it to create a component library to share among projects for a client
          - I managed to integrate **Vue** into a giant vanilla JS legacy project to improve UX for new components
          - I learned about the ups and downs of working **remotely**

      - layout: left
        title: init services
        link: www.theinit.com/
        sub_title: Developer
        caption: September 2012 - February 2016
        description: |
          I became an enthusiast of **agile** methodologies in init services.
          - I learned about **agile** by helping the organization transition to an agile mindset
          - I developed web applications with **J2EE**, Spring and Hibernate and mobile apps with **Ionic** Framework
          - I found **angular** and started separating back and front using REST and SPA
          - I discovered **git** and managed to migrate all the teams from SVN
          - I started using **Docker** to help with the setup of the development environment
          - I learned about **CI** and started using Jenkins

      - layout: left
        title: Grupo Versia
        link: www.versia.com/
        sub_title: Developer
        caption: January 2010 - September 2012
        description: |
          I joined Grupo Versia as the first member of a newly created **BI** team.
          - I helped the project manager gathering **requirements** and designing the architecture for various projects
          - I was responsible for several **ETL** processes with big data and speed needs with Pentaho
          - I worked with the client to create several BI **dashboards** with Pentaho

      - layout: left
        title: Thales
        link: www.thalesgroup.com
        sub_title: Developer
        caption: September 2007 - January 2010
        description: |
          Right out of the masters degree I started working for Thales as part of a client’s (Liberty Insurance) team. 
          - For a time I helped develop web apps to calculate insurance policies with **J2EE**, Struts, Hibernate
          - Then I joined the team responsible for the maintenance of the **web services** that allowed third parties to calculate insurance policies.

      - layout: left
        title: Universidad de Deusto
        link: www.deusto.es
        sub_title: Developer
        caption: September 2002 - June 2004
        description: |
          For a couple years in college I shared my time between studying and developing web apps for the intranet of the University of Deusto in **PHP** and **ASP**.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Deusto
        caption: 2006
        sub_title: Master in Development and Integration of Software Solutions
        description: |
          I prepared myself in this master degree more focused on practical knowledge.

      - layout: left
        title: University of Oulu
        caption: 2006
        sub_title: Computer Science
        description: |
          I spent the second half of the last year finishing my studies in University of Oulu (Finland). Making friends, polishing my english and learning the true meaning of the word *cold*.

      - layout: left
        title: University of Deusto
        caption: 2001 - 2006
        sub_title: Computer Science
        description: |
          I found my passion for programming and got hooked in the Open Source community while studing at the University of Deusto and working part time developing web apps for the intranet.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: babysizr
        sub_title: Android
        link: https://github.com/gexplorer/babysizr
        link_text: View on github
        description: |
          Set the due date and prepare for a weekly journey through the pregnancy where you can finally tell your geek friends how big (and beautiful) your baby is... and they will find it amusing!

      - layout: left
        title: babysizr
        sub_title: Google Assistant
        link: https://assistant.google.com/services/a/uid/000000eead6d2da9?hl=en_us&source=web
        link_text: View on Google Assistant
        description: |
          Babysizr let's you know the size of your incoming baby... in your Google Assistant!

      - layout: left
        title: simple-modeline
        sub_title: Emacs
        link: github.com/gexplorer/simple-modeline
        link_text: View on github
        description: |
          A simple mode-line configuration for Emacs.

      - layout: left
        title: flycheck-indicator
        sub_title: Emacs
        link: github.com/gexplorer/flycheck-indicator
        link_text: View on github
        description: |
          An Emacs minor-mode to get a fancy mode line indicator for Flycheck.

footer_show_references: true

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
